#!/bin/bash

# flux: --exclusive
# flux: -N 1
# flux: -g=1
# flux: -t 60m
# flux: -qpdebug
# flux: -B fractale

ml cce/21.0.0 cray-mpich/9.1.0 rocm/7.1.0 rccl/fast-env-slows-mpi

. .venvs/scaffoldvenv-tuo-pypi/bin/activate

# Use ccl plugin that we manually built with install-rccl.sh
export NCCL_NET_PLUGIN=../aws-ofi-nccl.git/install/lib/librccl-net.so

# Disable direct convolution benchmarking (should speedup warmup by a significant amount, does the below three options together)
# export MIOPEN_DEBUG_CONV_DIRECT=0
# Disable direct naive convolution benchmarking (naive_conv_ab_nonpacked_fwd_ndhwc_half_double_half.kd)
export MIOPEN_DEBUG_CONV_DIRECT_NAIVE_CONV_FWD=0
# Disable naive_conv_ab_nonpacked_bwd_ndhwc_half_double_half.kd
# export MIOPEN_DEBUG_CONV_DIRECT_NAIVE_CONV_BWD=0
# Disable naive_conv_ab_nonpacked_wrw_ndhwc_half_double_half.kd
export MIOPEN_DEBUG_CONV_DIRECT_NAIVE_CONV_WRW=0

torchrun-hpc -N 1 -n 1 $(which scaffold) generate_fractals -c $(pwd)/ScaFFold/configs/benchmark_default.yml

# Uncomment if you want torch profiling
#export PROFILE_TORCH=ON

torchrun-hpc -N 1 -n 4 --gpus-per-proc 1 $(which scaffold) benchmark -c $(pwd)/ScaFFold/configs/benchmark_default.yml
#torchrun-hpc -N 2 -n 4 --gpus-per-proc 1 $(which scaffold) benchmark -c $(pwd)/ScaFFold/configs/benchmark_default.yml
